// All learning guide entries live here.
// To add a source, copy an existing item block and fill in the fields.
//
// Fields:
//   title    — display name
//   author   — author, translator, director, or studio
//   year     — publication or release year
//   type     — Book | Novel | Novel Series | Film | TV Series | Video Series | etc.
//   accuracy — 1 (dramatized) to 5 (scholarly)
//   focus    — "mythology" | "history" | "both"
//   tag      — short label shown in the UI (Essential, Fiction, Caution, etc.)
//   note     — paragraph shown when the entry is expanded

export const categories = [
  {
    id: 'primary',
    label: 'Primary Sources',
    rune: 'ᚠ',
    color: '#C0922A',
    rgb: '192,146,42',
    items: [
      {
        title: 'The Prose Edda',
        author: 'Snorri Sturluson (trans. Jesse Byock or Anthony Faulkes)',
        year: 'c. 1220',
        type: 'Book',
        accuracy: 5,
        focus: 'mythology',
        tag: 'Essential',
        note: 'The single most important source for Norse mythology. Written by a 13th-century Icelandic scholar, it preserves the stories of Odin, Thor, Loki, and the cosmos in detail found nowhere else.',
        review: 'Add your review here.',
      },
      {
        title: 'The Poetic Edda',
        author: 'Trans. Carolyne Larrington or Jackson Crawford',
        year: 'c. 900–1100',
        type: 'Book',
        accuracy: 5,
        focus: 'mythology',
        tag: 'Essential',
        note: "A collection of Old Norse poems that predate Snorri's work. More raw and poetic than the Prose Edda — Crawford's translation is especially readable for modern audiences.",
      },
      {
        title: 'The Saga of the Volsungs',
        author: 'Trans. Jesse Byock',
        year: 'c. 1200s',
        type: 'Book',
        accuracy: 5,
        focus: 'both',
        tag: 'Mythology',
        note: "The great Norse heroic legend — the same material that inspired Wagner's Ring Cycle and Tolkien's legendarium. Dragons, cursed gold, doomed heroes.",
      },
      {
        title: "Ibn Fadlan's Journey to Russia",
        author: 'Ahmad ibn Fadlan (trans. Richard Frye)',
        year: '921 AD',
        type: 'Book',
        accuracy: 5,
        focus: 'history',
        tag: 'Primary Source',
        note: "An Arab diplomat's firsthand account of encountering the Rus' Vikings on the Volga. Contains the most vivid eyewitness description of a Viking ship burial ever recorded.",
      },
    ],
  },
  {
    id: 'nonfiction',
    label: 'Modern Scholarship',
    rune: 'ᚢ',
    color: '#6B9E8B',
    rgb: '107,158,139',
    items: [
      {
        title: 'Children of Ash and Elm',
        author: 'Neil Price',
        year: '2020',
        type: 'Book',
        accuracy: 5,
        focus: 'both',
        tag: 'Essential',
        note: "The definitive modern history of the Vikings by one of the world's leading Norse archaeologists. Beautifully written and rigorously researched — the best single-volume overview available.",
      },
      {
        title: 'The Age of the Vikings',
        author: 'Anders Winroth',
        year: '2014',
        type: 'Book',
        accuracy: 5,
        focus: 'history',
        tag: 'History',
        note: 'A concise, myth-busting account from a Yale historian. Winroth excels at separating popular legend from archaeological and documentary evidence.',
      },
      {
        title: 'The Viking World',
        author: 'Ed. Stefan Brink & Neil Price',
        year: '2008',
        type: 'Book',
        accuracy: 5,
        focus: 'both',
        tag: 'Reference',
        note: 'A scholarly encyclopedia covering everything from ship technology and law to gender and religion. Dense but invaluable as a reference work.',
      },
      {
        title: 'The Norse Myths',
        author: 'Kevin Crossley-Holland',
        year: '1980',
        type: 'Book',
        accuracy: 4,
        focus: 'mythology',
        tag: 'Mythology',
        note: 'A well-regarded literary retelling of the mythological cycle, with extensive scholarly notes. Ideal for readers who want the stories in flowing prose alongside academic context.',
      },
      {
        title: 'The Vikings: A History',
        author: 'Robert Ferguson',
        year: '2009',
        type: 'Book',
        accuracy: 4,
        focus: 'history',
        tag: 'History',
        note: 'A narrative history that follows the Viking Age from Lindisfarne to Stamford Bridge. Strong on cultural context, very readable.',
      },
      {
        title: "Jackson Crawford's YouTube Channel",
        author: 'Jackson Crawford (UC Boulder)',
        year: 'Ongoing',
        type: 'Video Series',
        accuracy: 5,
        focus: 'both',
        tag: 'Online',
        note: "A professional Norse philologist explains the language, myths, and culture directly from the sources. His 'Cowboy Heathen' style is uniquely accessible without sacrificing rigor.",
      },
    ],
  },
  {
    id: 'fiction',
    label: 'Historical Fiction',
    rune: 'ᚦ',
    color: '#8B6BB1',
    rgb: '139,107,177',
    items: [
      {
        title: 'The Long Ships',
        author: 'Frans G. Bengtsson',
        year: '1941–45',
        type: 'Novel',
        accuracy: 4,
        focus: 'history',
        tag: 'Fiction',
        note: "Widely considered the gold standard of Viking fiction. A Swedish novelist's epic tale of Orm Tostesson's adventures across Europe and the East — grounded in deep knowledge of the period.",
      },
      {
        title: 'The Saxon Stories (The Last Kingdom series)',
        author: 'Bernard Cornwell',
        year: '2004–2019',
        type: 'Novel Series',
        accuracy: 4,
        focus: 'history',
        tag: 'Fiction',
        note: "Follows Uhtred of Bebbanburg during the Danish invasions of Anglo-Saxon England. Cornwell's research is exceptional — the Viking portrayal is among the most grounded in popular fiction.",
      },
      {
        title: 'Norse Mythology',
        author: 'Neil Gaiman',
        year: '2017',
        type: 'Novel',
        accuracy: 4,
        focus: 'mythology',
        tag: 'Fiction',
        note: "Gaiman retells the core Norse myths — from the creation of the world to Ragnarök — drawing faithfully from the Prose and Poetic Eddas. The stories are largely accurate to their sources; what Gaiman adds is voice and momentum, not invention. A strong entry point before tackling the primary texts.",
      },
    ],
  },
  {
    id: 'film',
    label: 'Film',
    rune: 'ᚨ',
    color: '#B15B5B',
    rgb: '177,91,91',
    items: [
      {
        title: 'The Northman',
        author: 'Dir. Robert Eggers',
        year: '2022',
        type: 'Film',
        accuracy: 5,
        focus: 'both',
        tag: 'Highly Recommended',
        note: 'The most archaeologically and culturally accurate Viking film ever made. Eggers worked directly with Neil Price and other Norse scholars on costume, ritual, language, and material culture. Based on the Amleth legend.',
      },
      {
        title: 'Valhalla Rising',
        author: 'Dir. Nicolas Winding Refn',
        year: '2009',
        type: 'Film',
        accuracy: 3,
        focus: 'history',
        tag: 'Atmospheric',
        note: 'Atmospheric and brutal rather than documentary. More of an art film than a history lesson, but notable for avoiding fantasy clichés and depicting a credibly grim, pre-Christian Norse world.',
      },
      {
        title: 'The 13th Warrior',
        author: 'Dir. John McTiernan',
        year: '1999',
        type: 'Film',
        accuracy: 3,
        focus: 'history',
        tag: 'Adventure',
        note: "Based on Michael Crichton's novel 'Eaters of the Dead,' which fictionalizes Ibn Fadlan's account. The depiction of Norsemen is surprisingly grounded given its adventure-film framing.",
      },
    ],
  },
  {
    id: 'tv',
    label: 'Television',
    rune: 'ᚱ',
    color: '#4A7BAF',
    rgb: '74,123,175',
    items: [
      {
        title: 'The Last Kingdom',
        author: 'BBC / Netflix',
        year: '2015–2022',
        type: 'TV Series',
        accuracy: 4,
        focus: 'history',
        tag: 'Highly Recommended',
        note: "Adaptation of Cornwell's novels. Consistently one of the best-researched Viking Age dramas on screen — excellent on the cultural tension between Norse and Christian worlds in 9th-century England.",
      },
      {
        title: 'Norsemen (Vikingane)',
        author: 'NRK / Netflix',
        year: '2016–2020',
        type: 'TV Series (Comedy)',
        accuracy: 3,
        focus: 'history',
        tag: 'Comedy',
        note: "A Norwegian mockumentary comedy set in a Viking village. Played for laughs, but the production design and cultural details are surprisingly accurate — and it's genuinely funny.",
      },
      {
        title: 'Vikings (History Channel)',
        author: 'History Channel',
        year: '2013–2020',
        type: 'TV Series',
        accuracy: 2,
        focus: 'both',
        tag: 'Caution',
        note: 'Entertaining but takes significant creative liberties with chronology, geography, and character. Better as an introduction to the aesthetic world than as a history lesson. Watch with skepticism.',
      },
    ],
  },
  {
    id: 'documentary',
    label: 'Documentaries',
    rune: 'ᚲ',
    color: '#5E9E8B',
    rgb: '94,158,139',
    items: [
      {
        title: 'Vikings Unearthed',
        author: 'Nova/PBS',
        year: '2016',
        type: 'Documentary',
        accuracy: 5,
        focus: 'history',
        tag: 'Essential',
        note: 'Archaeology-driven Nova film tracing Norse expansion westward, with detailed coverage of L\'Anse aux Meadows in Newfoundland. Rigorous and compelling — one of the best single-film introductions to Viking history.',
      },
      {
        title: 'Viking Warrior Queen',
        author: 'PBS Secrets of the Dead',
        year: '2018',
        type: 'Documentary',
        accuracy: 5,
        focus: 'history',
        tag: 'Essential',
        note: 'Focused entirely on the Birka burial (Bj 581) and the DNA analysis that revealed the occupant was female — upending assumptions about Viking warrior culture. Specific, well-sourced, and genuinely important.',
      },
      {
        title: 'The Vikings Uncovered',
        author: 'BBC',
        year: '2016',
        type: 'Documentary',
        accuracy: 4,
        focus: 'history',
        tag: 'Reliable',
        note: 'Neil Oliver uses NASA satellite imagery and archaeology to trace Norse expansion across the North Atlantic to North America. Accessible without sacrificing accuracy.',
      },
      {
        title: 'Blood of the Vikings',
        author: 'BBC',
        year: '2001',
        type: 'Documentary Series',
        accuracy: 4,
        focus: 'history',
        tag: 'Reliable',
        note: '5-episode BBC series in which Julian Richards traces Viking settlement across Britain through DNA evidence and archaeology. A little dated but the science holds up and the scope is impressive.',
      },
      {
        title: 'Vikings: The Rise and Fall',
        author: 'National Geographic',
        year: '2022',
        type: 'Documentary Series',
        accuracy: 3,
        focus: 'both',
        tag: 'Mixed',
        note: '6-episode Nat Geo overview of Viking history from raids to settlement. Broad in scope and more dramatic in presentation than the PBS entries — useful as a general survey but verify specifics independently.',
      },
    ],
  },
]
